# Generated by Django 4.2.9 on 2024-01-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
        ),
    ]
