# Generated by Django 4.2.9 on 2024-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Goal Keeper'), ('forward', 'Forward'), ('middle', 'Middle'), ('defense', 'Defense'), ('striker', 'Striker')], max_length=100),
        ),
    ]
