# Generated by Django 4.2.9 on 2024-01-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_playeruser_height_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerUser',
        ),
    ]
