# Generated by Django 4.2.9 on 2024-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_games_goalsscored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalsscored',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='goalsscored',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Goal Keeper'), ('forward', 'Forward'), ('midfielder', 'Middle'), ('defense', 'Defense'), ('striker', 'Striker'), ('substitute', 'Substitute')], max_length=100),
        ),
    ]
