# Generated by Django 4.2.9 on 2024-01-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_game_id_goalsscored_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsscored',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='team.player'),
        ),
    ]
