# Generated by Django 4.2.9 on 2024-01-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_goalsscored_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsscored',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='team.player'),
        ),
    ]
