# Generated by Django 4.2.9 on 2024-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=15)),
            ],
        ),
    ]
