# Generated by Django 4.2.9 on 2024-01-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[], default='T-Shirt', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
