# Generated by Django 4.2.9 on 2024-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('XS', 'x-tra small'), ('M', 'Medium'), ('L', 'large'), ('XL', 'x-tra large'), ('X', 'x-tra')], default='S', max_length=100),
        ),
    ]
