# Generated by Django 4.2.9 on 2024-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(choices=[('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('', '')], default='', max_length=100),
        ),
    ]
