# Generated by Django 4.2.9 on 2024-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_order_payment_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Paypal'), (2, 'Card'), (3, 'Apple')], default=1),
        ),
    ]
