# Generated by Django 4.2.9 on 2024-01-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[(1, 'Paypal'), (2, 'Card'), (3, 'Apple')], default='Paypal', max_length=100),
        ),
    ]
