# Generated by Django 4.2.9 on 2024-02-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_remove_order_description_remove_order_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('XS', 'x-tra small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-tra large'), ('X', 'x-tra')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
