"""Manually call create_items() from this file to populate the eshop_item table with some items to buy"""
from eshop.models import Item
from random import choice, randint

shop_items = [
    {"item":"T-Shirt", "description":"Hot and sexy", "price" : 45, "size": "M"},
    {"item":"Cup", "description":"Sweet and useful", "price" : 35, "size": "L"},
    {"item":"Shoes", "description":"Fast and eye-catching", "price" : 75, "size": "S"},
    {"item":"Shorts", "description":"Awesome and necessary", "price" : 15, "size": "XL"},
    {"item":"Socks", "description":"Warm and tasty", "price" : 25, "size": "XS"},
]

sizes = ["XS", "S", "M", "L", "XL"]

descriptions = [
        "Bright and vibrant",
    "Energetic and dynamic",
    "Joyful and lively",
    "Cozy and inviting",
    "Refreshing and invigorating",
    "Cheerful and radiant",
    "Exquisite and charming",
    "Blissful and serene",
    "Graceful and elegant",
    "Inspiring and uplifting",
    "Effervescent and jubilant",
    "Soothing and comforting",
    "Luminous and effulgent",
    "Enchanting and delightful",
    "Whimsical and magical",
    "Rhythmic and harmonious",
    "Pristine and immaculate",
    "Tranquil and peaceful",
    "Vivacious and spirited",
    "Resplendent and dazzling",
    "Dynamic and invincible",
    "Captivating and magnetic",
    "Zestful and lively",
    "Pleasant and enjoyable",
    "Radiant and beaming",
    "Cherished and treasured",
    "Dazzling and glamorous",
    "Quaint and picturesque",
    "Effortless and graceful",
    "Radiant and jubilant",
    "Majestic and grand",
    "Vibrant and vivacious",
    "Wholesome and heartwarming",
    "Melodious and symphonic",
    "Breathtaking and awe-inspiring",
    "Stylish and sophisticated",
    "Epic and legendary",
    "Tranquil and idyllic",
    "Mellow and melodious",
    "Pleasant and harmonious",
    "Eclectic and versatile",
    "Dynamic and unstoppable",
    "Lively and effervescent",
    "Stellar and radiant",
    "Enthusiastic and passionate",
    "Enraptured and jubilant",
    "Glowing and radiant",
    "Serene and tranquil",
    "Magical and enchanting",
    "Cheery and upbeat",
    "Mesmerizing and captivating",
    "Idyllic and picturesque",
    "Graceful and poised",
    "Elegant and refined",
    "Pristine and unspoiled",
    "Glorious and magnificent",
    "Lighthearted and carefree",
    "Enlivening and invigorating",
    "Resplendent and opulent",
    "Joyful and ecstatic",
    "Zesty and dynamic",
    "Ethereal and celestial",
    "Pleasing and delightful",
    "Majestic and regal",
    "Sunny and delightful",
    "Glistening and sparkling",
    "Radiant and luminous",
    "Cheerful and jubilant",
    "Lively and spirited",
    "Thriving and flourishing",
    "Harmonious and balanced",
    "Inspirational and motivating",
    "Buoyant and cheerful",
    "Delightful and enchanting",
    "Spirited and exuberant",
    "Vivacious and zestful",
    "Captivating and alluring",
    "Dynamic and robust",
    "Luminous and radiant",
    "Blissful and euphoric",
    "Buoyant and effervescent",
    "Charming and delightful",
    "Radiant and splendid",
    "Serene and peaceful",
    "Elegant and sophisticated",
    "Pleasurable and enjoyable",
    "Invigorating and refreshing",
    "Exquisite and delightful",
    "Captivating and engaging",
    "Radiant and cheerful",
    "Lively and animated",
    "Glorious and triumphant",
    "Dynamic and vibrant",
    "Wholesome and heartening",
    "Soothing and calming",
    "Exuberant and lively",
    "Inspirational and uplifting",
    "Vibrant and dynamic",
    "Epic and monumental",
    "Cheery and buoyant",
    "Tranquil and idyllic",
    "Majestic and grand",
    "Lively and vivacious",
    "Enlivening and refreshing",
    "Delightful and charming",
    "Stunning and breathtaking",
    "Radiant and luminous",
    "Energetic and vibrant",
    "Dynamic and unstoppable",
    "Exquisite and alluring",
    "Harmonious and melodious",
    "Elegant and graceful",
    "Pristine and immaculate",
    "Joyful and ecstatic",
    "Captivating and enchanting",
    "Spirited and lively",
    "Buoyant and effervescent",
    "Glowing and radiant",
    "Charming and delightful",
    "Lighthearted and carefree",
    "Enchanting and delightful",
    "Radiant and jubilant",
    "Epic and legendary",
    "Zestful and lively",
    "Tranquil and idyllic",
    "Pleasant and enjoyable",
    "Radiant and beaming",
    "Cherished and treasured",
    "Dazzling and glamorous",
    "Quaint and picturesque",
    "Effortless and graceful",
    "Radiant and jubilant",
    "Majestic and grand",
    "Vibrant and vivacious",
    "Wholesome and heartwarming",
    "Melodious and symphonic",
    "Breathtaking and awe-inspiring",
    "Stylish and sophisticated",
    "Epic and legendary",
    "Tranquil and idyllic",
    "Mellow and melodious",
    "Pleasant and harmonious",
    "Eclectic and versatile",
    "Dynamic and unstoppable",
    "Lively and effervescent",
    "Stellar and radiant",
    "Enthusiastic and passionate",
    "Enraptured and jubilant",
    "Glowing and radiant",
    "Serene and tranquil",
    "Magical and enchanting",
    "Cheery and upbeat",
    "Mesmerizing and captivating",
    "Idyllic and picturesque",
    "Graceful and poised",
    "Elegant and refined",
    "Pristine and unspoiled",
    "Glorious and magnificent",
    "Lighthearted and carefree",
    "Enlivening and invigorating",
    "Resplendent and opulent",
    "Joyful and ecstatic",
    "Zesty and dynamic",
    "Ethereal and celestial",
    "Pleasing and delightful",
]

items = [
    "T-Shirt",
    "Jersey",
    "Hoodie",
    "Cap",
    "Scarf",
    "Mug",
    "Keychain",
    "Poster",
    "Flag",
    "Towel",
    "Backpack",
    "Water Bottle",
    "Blanket",
    "Mousepad",
    "Phone Case",
    "Sunglasses",
    "Beanie",
    "Umbrella",
    "Pillow",
    "Jacket",
    "Sticker Set",
    "Bracelet",
    "Lanyard",
    "Pop Socket",
    "Socks",
    "Baseball Cap",
    "Gym Bag",
    "Wallet",
    "Watch",
    "Headband",
    "Car Decal",
    "Pencil Set",
    "Puzzle",
    "Coaster Set",
    "Drawstring Bag",
    "Phone Stand",
    "Patch",
    "Lunchbox",
    "USB Drive",
    "Mini Soccer Ball",
    "Duffel Bag",
    "Belt",
    "Flask",
    "Poster"
]

def create_items():
    from random import randint  
    for i in range(5000):
        Item.objects.get_or_create(item=choice(items), description=choice(descriptions), price=randint(15, 75), size=choice(sizes))